Core_Clientes/Core_Clientes/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Clientes.Models
{
    public class ApplicationDbContext : Microsoft.EntityFrameworkCore.DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Cliente> Cliente { get; set; }
    }
}

Core_Clientes/Core_Clientes/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Clientes.Models
{
    public class Cliente
    {
        [Key]
        public int IdCliente { get; set; }

        [Required(ErrorMessage = "Ingresa nombre de cliente")]
        [Display(Name = "Nombre Cliente")]
        public string NombreCliente { get; set; }

        [Required(ErrorMessage = "Ingresa correo del cliente")]
        [Display(Name = "Correo")]
        [EmailAddress(ErrorMessage = "Ingresa un correo válido")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "Ingrese edad del cliente")]
        [Display(Name = "Edad")]
        [Range(20, 50)]
        public int EdadCliente { get; set; }

        [Required(ErrorMessage = "Ingresa crédito")]
        [Display(Name = "Crédito")]
        public int CreditoCliente { get; set; }
    }
}

Core_Clientes/Core_Clientes/Models/ErrorViewModel.cs
using System;

namespace Core_Clientes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core_Clientes/Core_Clientes/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Core_Clientes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Core_Clientes.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ClienteController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var displaydata = _db.Cliente.ToList();
            return View(displaydata);
        }

        [HttpGet] //Tiene un parametro
        public async Task<IActionResult> Index(string ctleSearch)
        {
            ViewData["GetClienteDetails"] = ctleSearch;
            var empquery = from x in _db.Cliente select x;
            if (!String.IsNullOrEmpty(ctleSearch))
            {
                empquery = empquery.Where(x => x.NombreCliente.Contains(ctleSearch) || x.Correo.Contains(ctleSearch));
            }
            return View(await empquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        //2)Crear cliente
        [HttpPost]
        public async Task<IActionResult> Create(Cliente nClte)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nClte);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(nClte);
        }

        //3) Detalles cliente
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDetail = await _db.Cliente.FindAsync(id);
            return View(getEmpDetail);
        }

        //4)Editar cliente
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCtleDetail = await _db.Cliente.FindAsync(id);
            return View(getCtleDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Cliente oldCtle)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldCtle);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldCtle);
        }

        //5)Eliminar cliente
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCtleDetails = await _db.Cliente.FindAsync(id);
            return View(getCtleDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getCtledetail = await _db.Cliente.FindAsync(id);
            _db.Cliente.Remove(getCtledetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Core_Clientes/Core_Clientes/Views/Cliente/Create.cshtml
@model Core_Clientes.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar un nuevo cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <!--<div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" class="form-control" />
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>-->
            <div class="form-group">
                <label asp-for="NombreCliente" class="control-label"></label>
                <input asp-for="NombreCliente" class="form-control" />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EdadCliente" class="control-label"></label>
                <input asp-for="EdadCliente" class="form-control" />
                <span asp-validation-for="EdadCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoCliente" class="control-label"></label>
                <input asp-for="CreditoCliente" class="form-control" />
                <span asp-validation-for="CreditoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Clientes/Core_Clientes/Views/Cliente/Delete.cshtml
@model Core_Clientes.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Cliente</h1>

<h3>¿Estás seguro de eliminar este cliente?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EdadCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EdadCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditoCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditoCliente)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a la lista</a>
    </form>
</div>

Core_Clientes/Core_Clientes/Views/Cliente/Detail.cshtml
@model Core_Clientes.Models.Cliente

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles del Cliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EdadCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EdadCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditoCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditoCliente)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Regresar a la lista</a>
</div>

Core_Clientes/Core_Clientes/Views/Cliente/Edit.cshtml
@model Core_Clientes.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" class="form-control" readonly/>
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreCliente" class="control-label"></label>
                <input asp-for="NombreCliente" class="form-control" />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EdadCliente" class="control-label"></label>
                <input asp-for="EdadCliente" class="form-control" />
                <span asp-validation-for="EdadCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoCliente" class="control-label"></label>
                <input asp-for="CreditoCliente" class="form-control" />
                <span asp-validation-for="CreditoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Clientes/Core_Clientes/Views/Cliente/Index.cshtml
@model IEnumerable<Core_Clientes.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

    <h1>Lista de Clientes</h1>

<p>
    <a asp-action="Create">Crear Nuevo Cliente</a>
</p>

<form asp-action="Index" method="get">
    <p>
        <i class="fade fa-search"></i>
        <input type="search" placeholder="Ingresa nombre o email..." name="ctleSearch" value="@ViewData["GetClienteDetails"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver todos</a>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EdadCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreditoCliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EdadCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreditoCliente)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdCliente }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Detalles", "Detail", new { id = item.IdCliente }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.IdCliente }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Core_Clientes/Core_Clientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core_Clientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cliente" asp-action="Index">Core_Clientes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Core_Clientes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>